title: yEAh Docs
email: docs@yeahgames.net
author: yEAh Dev Team
description: >
  Welcome to the official Documentation Archive Collection of the yEAh Games Library,
  host of the official yEAh Games documentation archive collection for bots, rules,
  servers, games, etc. Readable and searchable at https://docs.yeahgames.net.
  Want to find out about something in yEAh Games? The Docs collection is your best option.

baseurl: ""
url: "https://docs.yeahgames.net"

# Social
repo: "https://github.com/yEAh-Games/collections-docs"
github_user: "yEAh-Games"
github_repo: "collections-docs"
github_branch: "main"

# Optional
twitter: yEAhGames_
linkedin:
dockerhub:

# Versioning
version_params:
  version_menu: "Release"
  version_dir: v
  tocversion_dir: versions
  versioning: true

  # Disable so older versions cannot be searched
  allow_search: true  

  # Allow these versions to be searched
  search_versions:
    - "1.0"
    - "2.0"
  latest: "2.0"
  versions:
    - "2.0"
    - "1.0"

feedback: true

# Link to a privacy policy in footer, uncomment and define if wanted
privacy: https://www.yeahgames.net/privacy

# Google Analytics
# google-analytics: UA-XXXXXXXXXX

# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
logo: "https://i.imgur.com/XsnYzsI.png"
logo_pixels: 34
color: "#ff4747" # primary color for header, buttons

# Build settings
markdown: kramdown

# Permalinks and layouts
permalink: /posts/:year/:title/
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"

plugins:
 - jekyll-sitemap